spring:
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hexagonal_study
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

hexagonal:
  transferThreshold: 1000000
